---
apiVersion: v1
kind: Namespace
metadata:
  name: cyberark-swa
  labels:
    app.kubernetes.io/part-of: swa-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: swa-demo
  labels:
    app.kubernetes.io/part-of: swa-demo
