---
apiVersion: v1
kind: Namespace
metadata:
  name: swa-system
  labels:
    app.kubernetes.io/part-of: swa-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: swa-demo
  labels:
    app.kubernetes.io/part-of: swa-demo
